import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#0a0a0a',
  '--slot4-page-text': '#ffffff',
  '--slot4-panel-bg': '#151515',
  '--slot4-surface-bg': '#151515',
  '--slot4-muted-text': '#9d9d9d',
  '--slot4-soft-muted-text': '#666666',
  '--slot4-accent': '#fe97f1',
  '--slot4-accent-fill': '#fe97f1',
  '--slot4-accent-soft': '#3c2039',
  '--slot4-on-accent': '#0a0a0a',
  '--slot4-dark-bg': '#151515',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#202020',
  '--slot4-cream': '#151515',
  '--slot4-warm': '#151515',
  '--slot4-lavender': '#151515',
  '--slot4-gray': '#151515',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#0a0a0a',
  '--editable-page-text': '#ffffff',
  '--editable-container': '1400px',
  '--editable-border': '#1f1f1f',
  '--editable-nav-bg': '#0a0a0a',
  '--editable-nav-text': '#ffffff',
  '--editable-nav-active': '#fe97f1',
  '--editable-nav-active-text': '#0a0a0a',
  '--editable-cta-bg': '#fe97f1',
  '--editable-cta-text': '#0a0a0a',
  '--editable-search-bg': '#151515',
  '--editable-footer-bg': '#0a0a0a',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_3px_rgba(0,0,0,0.08)]',
  shadowStrong: 'shadow-[0_4px_18px_rgba(0,0,0,0.12)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-10',
    sectionY: 'py-20 sm:py-24 lg:py-[7.5rem]',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'editable-mono text-[11px] font-medium uppercase tracking-[0.14em] text-[#9fecff]',
    heroTitle: 'text-5xl font-normal leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-[5.25rem]',
    sectionTitle: 'text-4xl font-normal leading-[1.02] tracking-[-.04em] sm:text-5xl',
    body: 'text-base leading-7 text-[var(--slot4-muted-text)]',
    emphasis: 'editable-display italic font-normal',
  },
  surface: {
    card: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.surfaceBg}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.5rem] border border-white/10 ${editablePalette.darkBg} ${editablePalette.darkText}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-110`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:border-white/40`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-110`,
    ghost: 'inline-flex items-center justify-center gap-2 rounded-full px-4 py-2 text-sm font-medium text-[var(--slot4-muted-text)] transition hover:text-white',
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.5rem] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden ${editablePalette.mediaBg}`,
    ratio: 'aspect-[16/10]',
  },
  motion: {
    lift: 'transition duration-500 hover:border-white/30',
    fade: 'transition duration-500 hover:opacity-80',
    zoom: 'transition duration-700 group-hover:scale-[1.025]',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
